### ISSUE TITLE
Weakness in getProjects

### ISSUE THREAD

**Issue by erichirlemann** [rhyolight/appveyor-js-client#1]
Got a monitor on some jobs run by AppVeyor.
This monitor does about this:

```
appVeyorConn.getProjects(function (err, projects) {
        projects.forEach(
            function (project) {
                project.getLastBuildBranch('master', function (err, project) {
                    someProcessing();
                });
            }
        );
    }
);
```

It works perfectly during the day, but for several nights we have:

> TypeError: Cannot read property 'accountName' of null
>     at new AppVeyorProject (/home/sonarsource/wallboard/node_modules/appveyor-js-client/lib/project.js:5:35)
>     at /home/sonarsource/wallboard/node_modules/appveyor-js-client/lib/appveyor.js:40:20
>     at /home/sonarsource/wallboard/node_modules/appveyor-js-client/node_modules/lodash/index.js:2320:21
>     at baseFor (/home/sonarsource/wallboard/node_modules/appveyor-js-client/node_modules/lodash/index.js:2034:13)
>     at baseForOwn (/home/sonarsource/wallboard/node_modules/appveyor-js-client/node_modules/lodash/index.js:2088:14)
>     at baseEach (/home/sonarsource/wallboard/node_modules/appveyor-js-client/node_modules/lodash/index.js:1847:16)
>     at baseMap (/home/sonarsource/wallboard/node_modules/appveyor-js-client/node_modules/lodash/index.js:2319:7)
>     at Function.map (/home/sonarsource/wallboard/node_modules/appveyor-js-client/node_modules/lodash/index.js:6223:14)
>     at /home/sonarsource/wallboard/node_modules/appveyor-js-client/lib/appveyor.js:39:26
>     at Request.responseHandler [as _callback](/home/sonarsource/wallboard/node_modules/appveyor-js-client/lib/client.js:69:17)
>     at Request.self.callback (/home/sonarsource/wallboard/node_modules/appveyor-js-client/node_modules/request/request.js:344:22)
>     at Request.emit (events.js:98:17)
>     at Request.<anonymous> (/home/sonarsource/wallboard/node_modules/appveyor-js-client/node_modules/request/request.js:1239:14)
>     at Request.emit (events.js:117:20)
>     at IncomingMessage.<anonymous> (/home/sonarsource/wallboard/node_modules/appveyor-js-client/node_modules/request/request.js:1187:12)
>     at IncomingMessage.emit (events.js:117:20)

My first reading is that `getProjects` is capable of sending null `projectData` to  `AppVeyorProject` constructor. What do you think?

**Comment by rhyolight** [comment]
I think you are right. I think a filtering out the null values before calling the `map` function should fix this easily enough.

https://github.com/rhyolight/appveyor-js-client/blob/master/lib/appveyor.js#L35-L43

``` javascript
AppVeyor.prototype.getProjects = function(callback) {
    var client = this._client;
    client.get('projects', function(err, payload) {
        if (err) return callback(err);
        var noNulls = _.without(payload, null, undefined);
        callback(null, _.map(noNulls, function(projectData) {
            return new AppVeyorProject(projectData, client);
        }));
    });
};
```

I haven't tested this, but hopefully it works. ;)
